[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "peforth"
author = "H.C.Chen"
author-email = "hcchen5600@gmail.com"
home-page = "https://github.com/hcchengithub/peforth"
classifiers = ["License :: OSI Approved :: MIT License"]

